### ISSUE TITLE
Error at the SPI stage running `openfisca-uk-data frs_enhanced generate 2019`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-uk#592]
I'm guessing this is because I don't have the SPI?
```shell
(base) maxghenis@Maxs-MacBook-Pro openfisca-uk-data % openfisca-uk-data frs_enhanced generate 2019
INFO:root:Generating FRSEnhanced for year 2019
INFO:root:Loading FRS
INFO:root:Generating FRS dataset for year 2019
INFO:root:Loading FRS tables
INFO:root:Joining adult and child tables
INFO:root:Generating OpenFisca-UK variables
INFO:root:Completed FRS generation
INFO:root:Adding high incomes imputed from the SPI


Encountered an error:
Traceback (most recent call last):
  File "/Users/maxghenis/opt/anaconda3/bin/openfisca-uk-data", line 8, in <module>
    sys.exit(main())
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 28, in main
    raise e
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 25, in main
    return getattr(datasets[args.dataset], args.action)(*args.args)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/utils.py", line 111, in new_generate_func
    return generate_func(year, *args)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/datasets/frs/frs_enhanced/frs_enhanced.py", line 46, in generate
    pred_income = impute_incomes()
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/datasets/frs/frs_enhanced/spi_imputation.py", line 45, in impute_incomes
    spi = Microsimulation(dataset=SPI)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk/tools/simulation.py", line 95, in __init__
    year = self.default_year or max(dataset.years)
ValueError: max() arg is an empty sequence
```

From there I tried:
```shell
(base) maxghenis@Maxs-MacBook-Pro openfisca-uk-data % openfisca-uk-data spi generate 2019


Encountered an error:
Traceback (most recent call last):
  File "/Users/maxghenis/opt/anaconda3/bin/openfisca-uk-data", line 8, in <module>
    sys.exit(main())
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 28, in main
    raise e
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 25, in main
    return getattr(datasets[args.dataset], args.action)(*args.args)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/utils.py", line 111, in new_generate_func
    return generate_func(year, *args)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/datasets/spi/spi.py", line 24, in generate
    main = RawSPI.load(year, "main").fillna(0)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/utils.py", line 78, in load
    f"\n\nNo data available for year {year}. To download, run:\n\n\topenfisca-uk-data {cls.name} download {year}\n\nThis may require signing in with Google authentication if it is not publicly available."
Exception: 

No data available for year 2019. To download, run:

        openfisca-uk-data raw_spi download 2019

This may require signing in with Google authentication if it is not publicly available.
```
and from there:
```shell
(base) maxghenis@Maxs-MacBook-Pro openfisca-uk-data % openfisca-uk-data raw_spi download 2019


Encountered an error:
Traceback (most recent call last):
  File "/Users/maxghenis/opt/anaconda3/bin/openfisca-uk-data", line 8, in <module>
    sys.exit(main())
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 28, in main
    raise e
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/cli.py", line 25, in main
    return getattr(datasets[args.dataset], args.action)(*args.args)
  File "/Users/maxghenis/opt/anaconda3/lib/python3.7/site-packages/openfisca_uk_data/utils.py", line 173, in download
    "No acceptable version of the dataset could be found."
Exception: No acceptable version of the dataset could be found.
```

**Comment by vahid-ahmadi** [comment]
Closing as obsolete — the `openfisca-uk-data` CLI and the `FRSEnhanced` / `RawSPI` / `SPI` / `spi_imputation.py` modules in this traceback no longer exist. The package was renamed to [`policyengine-uk-data`](https://github.com/PolicyEngine/policyengine-uk-data) and the data pipeline was rewritten without the `generate`/`download` CLI surface.

Ongoing work on the imputation pipeline (including SPI / high-income anchoring) is tracked in #1621.
